<a href="https://colab.research.google.com/github/lukswi1/ds_bootcamp_udemy/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [138]:
import numpy as np
np.__version__

'1.19.5'

In [139]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'a

In [140]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [141]:
x = np.array([1,3])
x

array([1, 3])

In [142]:
print(x)

[1 3]


In [143]:
type(x)

numpy.ndarray

In [144]:
# wymiar array
x.ndim

1

In [145]:
# ksztalt     
x.shape

(2,)

In [146]:
# Liczba elementow  
x.size

2

In [147]:
# Typ zmiennych
x.dtype

dtype('int64')

In [148]:
x = np.array([1.3,2.3,1.4])
print(x)
print(x.dtype)

[1.3 2.3 1.4]
float64


In [149]:
# Macierz dwuwymiarowa
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [150]:
x.ndim

2

In [151]:
x.shape

(2, 2)

In [152]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [153]:
# 2 wiersze 3 kolumny
x.shape

(2, 3)

In [154]:
x = np.array(
    [[[4,3,1],
     [3,1,2]],

    [[4,1,3],
     [4,2,1]]]
)

x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [155]:
x.ndim

3

In [156]:
x.shape

(2, 2, 3)

In [157]:
# 6 Array typy danych
A = np.array([1,2,3], dtype ='float')
A.dtype



dtype('float64')

In [158]:
# Konwersja typu
A = np.array([1.1,2.2,3.5], dtype ='int')
A.dtype
A

array([1, 2, 3])

In [159]:
# Tworzenie tablic numpy


# Tworzenie pustej tablicy o zadanym ksztalcie
np.zeros(shape=(4,10),dtype='int')





array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [160]:
# Wypelnianie macierzy jedynkami
np.ones(shape=(5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [161]:
# tworzenie dowolnej macierzy z wypelnieniem dowolną wartoscia
np.full(shape=(3,3),fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [162]:
# tablica kolejnych wartosci
np.arange(start=10,stop=100,step=10)


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [163]:
# tablica rowno rozlozonych wartosci
np.linspace(start=0,stop=1,num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [164]:
A = np.arange(15)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [165]:
# chce mieć 3 wiersze i odpowiednią liczbę kolumn
# parametr -1
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [166]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [167]:
# 8. Operacje na tablicach
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(np.shape(A))
print(B)

(4,)
[ 3 -1  3  2]


In [168]:
# A + B
# A - B
# A * B
A / B
# A + 3

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [169]:
# Dodawanie tablic
np.add(A,B)

array([6, 0, 7, 4])

In [170]:
#  Odejmowanie tablic
np.subtract(A,B)

array([0, 2, 1, 0])

In [171]:
# Mnożenie tablic
np.multiply(A, B) 

array([ 9, -1, 12,  4])

In [172]:
# Dzielenie tablic 
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [173]:
# Mnożenie macieżowe
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [174]:
# Mnożenie elemnt po elemencie
X * Y

array([[6, 0],
       [2, 0]])

In [175]:
# Mnożenie macierzowe
# np.dot(X,Y)
# X.dot(Y)
X @ Y


array([[  3,   6],
       [-12,   0]])

In [176]:
#  9. Generowanie liczb pseudolosowych - np.random

# Ustawienie ziarna
np.random.seed(0)

In [177]:
# Losowa wartosc z rozkladu normalnego (10-wiersze 4 kolumny)
np.random.randn(10,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [178]:
np.random.rand(10, 2)

array([[0.31542835, 0.36371077],
       [0.57019677, 0.43860151],
       [0.98837384, 0.10204481],
       [0.20887676, 0.16130952],
       [0.65310833, 0.2532916 ],
       [0.46631077, 0.24442559],
       [0.15896958, 0.11037514],
       [0.65632959, 0.13818295],
       [0.19658236, 0.36872517],
       [0.82099323, 0.09710128]])

In [179]:
np.random.randint(low = 10, high = 100, size = 10)

array([60, 46, 44, 58, 13, 52, 87, 31, 83, 10])

In [180]:
#  Zwracanie losowego elemntu z listy, dowolny format
np.random.choice([4, 2, 1, 4])

1

In [181]:
data = np.arange(10)
# Losowe przetasaowanie danych
np.random.shuffle(data)
data

array([0, 5, 8, 4, 6, 1, 9, 3, 7, 2])

In [182]:
# 10. Podstawowe funkcje
np.exp(1)

2.718281828459045

In [183]:
# Pierwiastek
np.sqrt(9)

3.0

In [184]:
# Czy gdziekolwiek jest false
np.all([2, 3, 1])

True

In [185]:
# Czy jakikolwiek obiekt jest prawdą
np.any([0, 0, 0])

False

In [186]:
bool(0)

False

In [187]:
A = np.random.rand(5)
A

array([0.21682214, 0.56518887, 0.86510256, 0.50896896, 0.91672295])

In [188]:
# Indeks największej wartości
A[np.argmax(A)]

0.9167229540194608

In [189]:
# Sortowanie - wskazuje indeksy
np.argsort(A)

array([0, 3, 1, 2, 4])

In [190]:
# Wartość największa i najmniejsza tablicy
# np.max(A)
# np.min(A)
# np.median(A)
np.std(A)

0.2552866660701157

In [191]:
# 11 Indeksowanie i wycinanie tablic
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [192]:
#  Konkretny indeks
# A[5]

# Zakres indeksów
# A[start:stop]
A[2:]

# Indeks na ktorym chcemy skonczyć
# A[:stop]

# Indeks od którego chcemy zacząć
# A[start:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [193]:
# Lista 
A[[0,2]]

array([0, 2])

In [194]:
# Ostatni element
A[-1]

19

In [195]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [196]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [197]:
# Wycinanie wiersza
A[1]

array([5, 6, 7, 8, 9])

In [198]:
# Wycinanie kolumny
A[:,2]
# Wycinanie ostatniej kolumny
# A[:,-1]
# Wycinanie po indeksie
# A[1,2]

array([ 2,  7, 12, 17])

In [199]:
# Wycinanie fragmentu tablicy
A[1:3, 1:4]



array([[ 6,  7,  8],
       [11, 12, 13]])

In [200]:
# Przypisanie nowej wartosci na konkretnym indeksie
# A
# A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [201]:
# 12 Iteracja po tablicach
for row in A:
  print(row[:2])


[0 1]
[5 6]
[10 11]
[15 16]


In [202]:
# iterowanie po elementach
for item in A.flat:
  print(item)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [203]:
# Zmiana rozmiaru tablic
# A.shape
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [208]:
# Transpozycja
A.T
# Wypłaszczenie danych
# A.ravel()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [222]:
# Maski logiczne
B = np.arange(start=-10,stop = 10, step=0.5)
B = B.reshape(10,-1)
B

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [224]:
B > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [225]:
# Wybór wartości tablicy według warunku
B[B>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [229]:
# Maska elemntów przedziału -5 5
# np.bitwise_and(B>-5, B<5)
B[np.bitwise_and(B>-5, B<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])