<a href="https://colab.research.google.com/github/lukswi1/ds_bootcamp_udemy/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
v1 = np.array([0,4])
v1

array([0, 4])

In [ ]:
# Norma w przestrzeni R^2
np.linalg.norm(v1)

4.0

In [ ]:
# Długość wektora w R^3
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

In [ ]:
# Odleglosc dwóch punktów napłaszczyźnie
p = np.array([3,0])
q = np.array([0,4])
np.linalg.norm(p-q)

5.0

In [ ]:
# Odleglosc dwóch punktów w przestrzenii R^n
p = np.array([3,0,1])
q = np.array([0,4,2])
np.linalg.norm(p-q)

5.0990195135927845

In [ ]:
# Mnożenie macierzy
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z = np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [ ]:
# Wyznacznik macierzy - 
A = np.array([[2,4],[-1,3]])
A

array([[ 2,  4],
       [-1,  3]])

In [ ]:
round(np.linalg.det(A))

10

In [ ]:
# Ślad macierzy - suma na glownej przekątnej
np.trace(A)

5

In [ ]:
# Macierz jednostkowa - kwadratowa i wsp na przekątnej = 1
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# Macierz odwrotna
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
# Czy na pewno odwrotna
np.set_printoptions(precision=4,suppress=True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Transpozycja macierzy - zamiana wierszy na kolumny i kolumny na wiersze
A.T

array([[ 2, -1],
       [ 4,  3]])

In [11]:
# Układy równań
A = np.array([[2,4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [6]:
B = np.array([[10], [-1]])
B

array([[10],
       [-1]])

In [12]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.16666667,  0.66666667],
       [ 0.16666667, -0.33333333]])

In [13]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])